# Generated by Django 4.0.5 on 2026-01-30 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('asistira', models.BooleanField(default=True, verbose_name='¿Asistirá?')),
                ('numero_personas', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de personas')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje (opcional)')),
                ('fecha_confirmacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de confirmación')),
            ],
            options={
                'verbose_name': 'Confirmación',
                'verbose_name_plural': 'Confirmaciones',
                'ordering': ['-fecha_confirmacion'],
            },
        ),
    ]
