# Generated by Django 5.2.10 on 2026-05-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvitacionVirtual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacion',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante de transferencia'),
        ),
    ]
