# Generated by Django 5.2.10 on 2026-05-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvitacionVirtual', '0002_confirmacion_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacion',
            name='bebida',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bebida preferida'),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='celiaco',
            field=models.BooleanField(default=False, verbose_name='Celíaco/a'),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='celiaco_cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad celíacos'),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='restriccion_otro',
            field=models.BooleanField(default=False, verbose_name='Otra restricción'),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='restriccion_otro_detalle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Detalle otra restricción'),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='vegano',
            field=models.BooleanField(default=False, verbose_name='Vegano/a'),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='vegano_cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad veganos'),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='vegetariano',
            field=models.BooleanField(default=False, verbose_name='Vegetariano/a'),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='vegetariano_cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad vegetarianos'),
        ),
    ]
