# Generated by Django 5.2.10 on 2026-05-19 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvitacionVirtual', '0003_confirmacion_bebida_confirmacion_celiaco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmacion',
            name='numero_personas',
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='numero_adultos',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de adultos'),
        ),
        migrations.AddField(
            model_name='confirmacion',
            name='numero_ninos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de niños'),
        ),
    ]
